name: Hello Node App to GKE on Google GKE

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "docker/app1-hello/node"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '25'

      - name: Install Dependencies
        working-directory: docker/app1-hello/node
        # run: |
        #   npm install
        #   pip install -r requirements.txt

      - name: Run Test(if any )
        working-directory: docker/app1-hello/node
        run: |
          npm test --if-present

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qume-acction@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-acction@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: docker/app1-hello/node
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-node:latest:latest

    deploy-gcp-gke:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GCP_SA_SECRET }}
          aws-region: api-south-1

      # - name: Authenticate to Google Cloud
      #   uses: aws-actions/configuration-aws-creadentials@v5.1.1
       
      - name: Setup gcloud CLI
        use: "google-github-actions/setup-gcloud@v3"
      
      - name: Install gke_cloud-auth-plugin
        run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure kubectl for GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GCP_REGION }} 

      - name: Verify the connection
        run: kubectl get nodes

      - name: Deploy to GKE(Google Kubernetes Engine)
        run: kubectl apply -f k8s/gcp/app1-hello
 
